variable "aws_region" {
  type    = string
  default = "eu-central-1"
}

variable "jenkins_ssh_public_key" {
  type      = string
  sensitive = true
  default   = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFUERwBLsifz13f9YBvc2w5YGjgN/rHBO2F9ku+MPi0u jenkins@cloud-infra"
}

variable "common_tags" {
  type = map(string)
  default = {
    Project     = "cloud-infra"
    Environment = "production"
    ManagedBy   = "terraform"
  }
}

variable "acm_certificate_arn" {
  description = "ACM certificate ARN for the public HTTPS ingress (passed to Helm via ArgoCD). Leave empty to skip."
  type        = string
  default     = ""
}

variable "use_self_signed_cert" {
  description = "When true and no ACM ARN provided, generate a self-signed cert and import to ACM automatically."
  type        = bool
  default     = true
}

variable "certificate_common_name" {
  description = "Common Name (CN) for the self-signed certificate when generated by Terraform."
  type        = string
  default     = "microblog.local"
}
variable "app_image_repository" {
  description = "Container image repository to deploy (overrides Helm value via ArgoCD). Empty to use chart default."
  type        = string
  default     = "ghcr.io/cloud-infra-assignment/microblog"
}

variable "app_image_tag" {
  description = "Container image tag to deploy (overrides Helm value via ArgoCD). Empty to use chart default."
  type        = string
  default     = "6"
}

variable "ghcr_username" {
  description = "GitHub Container Registry username for image pulls (used to create imagePullSecret)"
  type        = string
  default     = ""
}

variable "ghcr_token" {
  description = "GitHub Container Registry token (PAT) for image pulls (used to create imagePullSecret)"
  type        = string
  sensitive   = true
  default     = ""
}